const users = [
  {
    id: 1,
    username: "JohnDoe",
    createDate: "2024-05-01",
    segment: "new",
    imageUrl: "https://example.com/user1.jpg",
  },
  {
    id: 2,
    username: "AliceSmith",
    createDate: "2024-05-02",
    segment: "new",
    imageUrl: "https://example.com/user2.jpg",
  },
  {
    id: 3,
    username: "MichaelJohnson",
    createDate: "2024-05-03",
    segment: "new",
    imageUrl: "https://example.com/user3.jpg",
  },
  {
    id: 4,
    username: "EmilyBrown",
    createDate: "2024-05-04",
    segment: "old",
    imageUrl: "https://example.com/user4.jpg",
  },
  {
    id: 5,
    username: "WilliamDavis",
    createDate: "2024-05-05",
    segment: "old",
    imageUrl: "https://example.com/user5.jpg",
  },
  {
    id: 6,
    username: "SophiaWilson",
    createDate: "2024-05-06",
    segment: "old",
    imageUrl: "https://example.com/user6.jpg",
  },
  {
    id: 7,
    username: "JamesTaylor",
    createDate: "2024-05-07",
    segment: "new",
    imageUrl: "https://example.com/user7.jpg",
  },
  {
    id: 8,
    username: "EmmaAnderson",
    createDate: "2024-05-08",
    segment: "old",
    imageUrl: "https://example.com/user8.jpg",
  },
  {
    id: 9,
    username: "BenjaminClark",
    createDate: "2024-05-09",
    segment: "new",
    imageUrl: "https://example.com/user9.jpg",
  },
  {
    id: 10,
    username: "OliviaMartinez",
    createDate: "2024-05-10",
    segment: "old",
    imageUrl: "https://example.com/user10.jpg",
  },
  {
    id: 11,
    username: "NoahHernandez",
    createDate: "2024-05-11",
    segment: "old",
    imageUrl: "https://example.com/user11.jpg",
  },
  {
    id: 12,
    username: "IsabellaYoung",
    createDate: "2024-05-12",
    segment: "new",
    imageUrl: "https://example.com/user12.jpg",
  },
  {
    id: 13,
    username: "LiamKing",
    createDate: "2024-05-13",
    segment: "old",
    imageUrl: "https://example.com/user13.jpg",
  },
  {
    id: 14,
    username: "AvaGarcia",
    createDate: "2024-05-14",
    segment: "new",
    imageUrl: "https://example.com/user14.jpg",
  },
  {
    id: 15,
    username: "ElijahLopez",
    createDate: "2024-05-15",
    segment: "new",
    imageUrl: "https://example.com/user15.jpg",
  },
  {
    id: 16,
    username: "CharlottePerez",
    createDate: "2024-05-16",
    segment: "old",
    imageUrl: "https://example.com/user16.jpg",
  },
  {
    id: 17,
    username: "AlexanderSanchez",
    createDate: "2024-05-17",
    segment: "old",
    imageUrl: "https://example.com/user17.jpg",
  },
  {
    id: 18,
    username: "MiaRamirez",
    createDate: "2024-05-18",
    segment: "new",
    imageUrl: "https://example.com/user18.jpg",
  },
  {
    id: 19,
    username: "MasonTorres",
    createDate: "2024-05-19",
    segment: "old",
    imageUrl: "https://example.com/user19.jpg",
  },
  {
    id: 20,
    username: "HarperFlores",
    createDate: "2024-05-20",
    segment: "old",
    imageUrl: "https://example.com/user20.jpg",
  },
];

export default users;
